#!/usr/bin/python3

import matplotlib.pyplot as plt
import sys
import os


outdir = sys.argv[1].rstrip("/")

ypad = 0.1
try:
    ypad = float(sys.argv[2])
except IndexError:
    pass

dirlist = list()
for name in os.listdir(outdir):
    dirname = os.path.join(outdir,name)
    if os.path.isdir(dirname):
        dirlist.append(dirname)

for subdir in dirlist:
    pngdir = os.path.join(subdir,"png")
    try:
        os.mkdir(pngdir)
    except FileExistsError:
        pass

    for filename in os.listdir(subdir):
        X = list()
        Y = list()
        
        xmin = 0.0
        xmax = 0.0
        ymin = 0.0
        ymax = 0.0

        if (filename.endswith(".txt")):
            for lines in open(os.path.join(subdir,filename),'r'):
                values = lines.split()
                
                xcurr = float(values[0])
                if (xcurr < xmin):
                    xmin = xcurr
                if (xcurr > xmax):
                    xmax = xcurr
                
                ycurr = float(values[1])
                if (ycurr < ymin):
                    ymin = ycurr
                if (ycurr > ymax):
                    ymax = ycurr

        if (filename.endswith(".txt")):
            for lines in open(os.path.join(subdir,filename),'r'):
                values = lines.split()
                X.append(float(values[0]))
                Y.append(float(values[1]))
            
            plt.xlim(xmin,xmax)
            plt.ylim(ymin-ypad,ymax+ypad)
            plt.plot(X,Y)
            plt.savefig(os.path.join(pngdir,filename.rstrip(".txt") + ".png"))
            plt.clf()

        #TODO: call convert
